### ISSUE TITLE
TypeError: googleMagnetRes.flat is not a function

### ISSUE THREAD

**Issue by aniforverizon** [gustavofabro/get-torrents-cli#7]
PS C:\Users\lenovo\proxysite-url-checker> get-torrents https://www.1377x.to/search/queen%20hindi%20/1/
Extracting magnets links...
TypeError: googleMagnetRes.flat is not a function
    at getMagnetDto (C:\Users\lenovo\AppData\Roaming\npm\node_modules\get-torrents-cli\app\magnet_extract.js:65:28)    
    at Promise.all.then (C:\Users\lenovo\AppData\Roaming\npm\node_modules\get-torrents-cli\app\magnet_extract.js:58:47)
    at process._tickCallback (internal/process/next_tick.js:68:7)

![image](https://user-images.githubusercontent.com/43361858/92435086-1c0ec900-f1bf-11ea-93f5-ea14624cd6ba.png)

**Comment by gustavofabro** [comment]
What version of Node JS are you using?

**Comment by aniforverizon** [comment]
PS C:\Users\lenovo> node -v
v10.16.3
